controllers:
     resource:
         path: ../src/Controller/
         namespace: App\Controller
     type: attribute
# app_index:
#     path: /index
#     controller: App\Controller\IndexController::index
# app_about:
#     path: /about
#     controller: App\Controller\IndexController::about